package com.pdfnotes.app.ui.documents

import android.content.Context
import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.grid.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.*
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import com.pdfnotes.app.domain.model.Document

@Composable fun DocumentListScreen(viewModel:DocumentListViewModel,onOpenDocument:(Document)->Unit){val documents by viewModel.documents.collectAsState();val context=LocalContext.current;var query by remember{mutableStateOf("")};var grid by remember{mutableStateOf(true)};var sortMenu by remember{mutableStateOf(false)};val picker=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){u:Uri?->if(u!=null)viewModel.onDocumentPicked(u.toString(),queryDisplayName(context,u)?:"Документ.pdf")};val filtered=documents.filter{it.displayName.contains(query,true)};Column(Modifier.fillMaxSize().padding(horizontal=28.dp,vertical=26.dp)){Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Документы",style=MaterialTheme.typography.headlineLarge);Spacer(Modifier.height(4.dp));Text("Ваши PDF-файлы в одном месте",color=MaterialTheme.colorScheme.onSurfaceVariant)};FilledIconButton(onClick={picker.launch(arrayOf("application/pdf"))},modifier=Modifier.size(46.dp)){Icon(Icons.Default.Add,"Добавить PDF")}};Spacer(Modifier.height(20.dp));Row(verticalAlignment=Alignment.CenterVertically){OutlinedTextField(query,{query=it},Modifier.weight(1f).height(50.dp),singleLine=true,leadingIcon={Icon(Icons.Default.Search,null)},placeholder={Text("Поиск документов")},shape=MaterialTheme.shapes.medium);Spacer(Modifier.width(10.dp));Box{FilledTonalButton(onClick={sortMenu=true}){Text("По дате");Spacer(Modifier.width(4.dp));Icon(Icons.Default.ExpandMore,null)};DropdownMenu(sortMenu,{sortMenu=false}){DropdownMenuItem({Text("По дате")},{sortMenu=false});DropdownMenuItem({Text("По имени")},{sortMenu=false});DropdownMenuItem({Text("По размеру")},{sortMenu=false})}};Spacer(Modifier.width(8.dp));IconButton(onClick={grid=true}){Icon(Icons.Default.GridView,"Сетка",tint=if(grid)MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.onSurfaceVariant)};IconButton(onClick={grid=false}){Icon(Icons.Default.ViewList,"Список",tint=if(!grid)MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.onSurfaceVariant)}};Spacer(Modifier.height(22.dp));if(filtered.isEmpty()){Box(Modifier.fillMaxSize(),Alignment.Center){EmptyState{picker.launch(arrayOf("application/pdf"))}}}else if(grid){LazyVerticalGrid(columns=GridCells.Adaptive(185.dp),horizontalArrangement=Arrangement.spacedBy(16.dp),verticalArrangement=Arrangement.spacedBy(18.dp),contentPadding=PaddingValues(bottom=90.dp)){items(filtered,key={it.id}){DocumentCard(it,onOpenDocument)}}}else{androidx.compose.foundation.lazy.LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp),contentPadding=PaddingValues(bottom=90.dp)){items(filtered.size){DocumentRow(filtered[it],onOpenDocument)}}};Spacer(Modifier.weight(1f));FloatingActionButton(onClick={picker.launch(arrayOf("application/pdf"))},modifier=Modifier.align(Alignment.End),containerColor=MaterialTheme.colorScheme.primary){Icon(Icons.Default.Add,null)}}}
@Composable private fun DocumentCard(doc:Document,onOpen:(Document)->Unit){Card(onClick={onOpen(doc)},shape=MaterialTheme.shapes.medium,colors=CardDefaults.cardColors(MaterialTheme.colorScheme.surface),border=BorderStroke(1.dp,MaterialTheme.colorScheme.outlineVariant)){Column(Modifier.padding(10.dp)){Box(Modifier.fillMaxWidth().height(190.dp).clip(MaterialTheme.shapes.small).background(Brush.verticalGradient(listOf(Color(0xFFE7E9EE),Color(0xFFB9BEC8)))),Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Default.PictureAsPdf,null,Modifier.size(54.dp),tint=Color(0xFFD84B52));Text("PDF",color=Color(0xFF343944),style=MaterialTheme.typography.titleMedium)};Surface(Modifier.align(Alignment.TopEnd).padding(8.dp),color=Color.White.copy(.92f),shape=MaterialTheme.shapes.small){Text("PDF",Modifier.padding(horizontal=7.dp,vertical=3.dp),color=Color(0xFFD84B52),style=MaterialTheme.typography.labelLarge)}};Spacer(Modifier.height(10.dp));Text(doc.displayName,maxLines=2,overflow=TextOverflow.Ellipsis,style=MaterialTheme.typography.titleMedium);Spacer(Modifier.height(4.dp));Text("${doc.sizeBytes/1024/1024} МБ • ${doc.pageCount} стр.",color=MaterialTheme.colorScheme.onSurfaceVariant,style=MaterialTheme.typography.bodyMedium)}}}
@Composable private fun DocumentRow(doc:Document,onOpen:(Document)->Unit){Card(onClick={onOpen(doc)},Modifier.fillMaxWidth(),colors=CardDefaults.cardColors(MaterialTheme.colorScheme.surface)){ListItem(headlineContent={Text(doc.displayName)},supportingContent={Text("${doc.pageCount} страниц • ${formatBytes(doc.sizeBytes)}")},leadingContent={Icon(Icons.Default.PictureAsPdf,null,tint=Color(0xFFFF6670))},trailingContent={Icon(Icons.Default.ChevronRight,null)})}}
@Composable private fun EmptyState(onAdd:()->Unit){Column(horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Default.Description,null,Modifier.size(60.dp),tint=MaterialTheme.colorScheme.primary);Spacer(Modifier.height(12.dp));Text("Нет документов",style=MaterialTheme.typography.titleLarge);Text("Добавьте PDF, чтобы начать работу",color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.height(16.dp));Button(onClick=onAdd){Icon(Icons.Default.Add,null);Spacer(Modifier.width(6.dp));Text("Добавить PDF")}}}
private fun queryDisplayName(context:Context,uri:Uri):String?{val p=context.contentResolver.query(uri,arrayOf("_display_name"),null,null,null)?:return null;return p.use{if(it.moveToFirst())it.getString(0) else null}}
private fun formatBytes(bytes:Long):String=when{bytes>=1024*1024->"%.1f МБ".format(bytes/1024f/1024f);bytes>=1024->"%.0f КБ".format(bytes/1024f);else->"$bytes Б"}
