package com.pdfnotes.app.ui.notes

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.pdfnotes.app.domain.model.Document

@Composable fun NotesScreen(documents:List<Document>){var selected by remember{mutableStateOf<Document?>(documents.firstOrNull())};LaunchedEffect(documents){if(selected==null)selected=documents.firstOrNull()};Column(Modifier.fillMaxSize()){Row(Modifier.fillMaxWidth().height(64.dp).padding(horizontal=22.dp),verticalAlignment=androidx.compose.ui.Alignment.CenterVertically){Text("Конспектирование",style=MaterialTheme.typography.titleLarge);Spacer(Modifier.weight(1f));IconButton(onClick={}){Icon(Icons.Default.AutoAwesome,null)};IconButton(onClick={}){Icon(Icons.Default.Share,null)}};HorizontalDivider(color=MaterialTheme.colorScheme.outlineVariant);Row(Modifier.fillMaxSize()){Surface(Modifier.width(270.dp).fillMaxHeight(),color=MaterialTheme.colorScheme.surface){LazyColumn(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(4.dp)){item{Text("Конспект",style=MaterialTheme.typography.titleMedium);Spacer(Modifier.height(10.dp))};items(documents){d->ListItem(headlineContent={Text(d.displayName,maxLines=1)},supportingContent={Text("${d.pageCount} страниц")},leadingContent={Icon(Icons.Default.Description,null)},colors=ListItemDefaults.colors(containerColor=if(selected?.id==d.id)MaterialTheme.colorScheme.primaryContainer else MaterialTheme.colorScheme.surface),modifier=Modifier.fillMaxWidth().clickable{selected=d})};item{Spacer(Modifier.height(10.dp));TextButton(onClick={}){Icon(Icons.Default.Add,null);Spacer(Modifier.width(5.dp));Text("Добавить раздел")}}}};selected?.let{doc->Column(Modifier.fillMaxSize().padding(28.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){Text("1. Введение",style=MaterialTheme.typography.headlineMedium);Text("${doc.displayName} • ${doc.pageCount} страниц",color=MaterialTheme.colorScheme.onSurfaceVariant);Card(Modifier.fillMaxWidth(),colors=CardDefaults.cardColors(MaterialTheme.colorScheme.surface)){Column(Modifier.padding(22.dp),verticalArrangement=Arrangement.spacedBy(13.dp)){Text("• Искусственный интеллект — область компьютерных наук.");Text("• Цель: создание интеллектуальных машин.");Text("• Задачи: обучение, рассуждение и решение проблем.");HorizontalDivider();Text("Ключевые термины",style=MaterialTheme.typography.titleMedium);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){AssistChip(onClick={},label={Text("ИИ")});AssistChip(onClick={},label={Text("Машинное обучение")});AssistChip(onClick={},label={Text("Нейронные сети")})}}};Button(onClick={},Modifier.fillMaxWidth()){Icon(Icons.Default.AutoAwesome,null);Spacer(Modifier.width(8.dp));Text("Сформировать конспект")}}}?:Box(Modifier.fillMaxSize()){Text("Добавьте PDF, чтобы создать конспект")}}}}
